#define DECLARE_COMMON_LIBRARY \
		USE_LOGGER_INIT \

#ifdef USE_LOGGER_INIT
const char* LOGGING_TYPE_VERBOSE = "VERBOSE";
const char* LOGGING_TYPE_DEBUG = "DEBUG";
const char* LOGGING_TYPE_INFO = "INFO";
const char* LOGGING_TYPE_WARNING = "WARNING";
const char* LOGGING_TYPE_ERROR = "ERROR";
const char* LOGGING_TYPE_FATAL = "FATAL";
const char* LOGGING_TYPE_SUCCESS = "SUCCESS";
#endif
